/**
 * PF2e Action Display Names
 * Maps action slugs to their display names
 */

export const PF2E_ACTION_DISPLAY_NAMES = {
  seek: 'Seek',
  'sense-direction': 'Sense Direction',
  balance: 'Balance',
  'tumble-through': 'Tumble Through',
  'maneuver-in-flight': 'Maneuver in Flight',
  squeeze: 'Squeeze',
  'recall-knowledge': 'Recall Knowledge',
  'decipher-writing': 'Decipher Writing',
  'identify-magic': 'Identify Magic',
  'learn-spell': 'Learn a Spell',
  climb: 'Climb',
  'force-open': 'Force Open',
  grapple: 'Grapple',
  'high-jump': 'High Jump',
  'long-jump': 'Long Jump',
  shove: 'Shove',
  swim: 'Swim',
  trip: 'Trip',
  disarm: 'Disarm',
  repair: 'Repair',
  craft: 'Craft',
  'identify-alchemy': 'Identify Alchemy',
  'create-a-diversion': 'Create a Diversion',
  impersonate: 'Impersonate',
  lie: 'Lie',
  feint: 'Feint',
  'gather-information': 'Gather Information',
  'make-an-impression': 'Make an Impression',
  request: 'Request',
  coerce: 'Coerce',
  demoralize: 'Demoralize',
  'administer-first-aid': 'Administer First Aid',
  'treat-disease': 'Treat Disease',
  'treat-poison': 'Treat Poison',
  'treat-wounds': 'Treat Wounds',
  'command-an-animal': 'Command an Animal',
  perform: 'Perform',
  'create-forgery': 'Create Forgery',
  subsist: 'Subsist',
  'conceal-an-object': 'Conceal an Object',
  hide: 'Hide',
  sneak: 'Sneak',
  track: 'Track',
  'cover-tracks': 'Cover Tracks',
  'palm-an-object': 'Palm an Object',
  steal: 'Steal',
  'pick-a-lock': 'Pick a Lock',
  'disable-device': 'Disable Device',
};
